INSERT INTO `amenities` (`name`, `description`) VALUES
('Swimming Pool', 'Enjoy a refreshing swim in the private or shared pool.'),
('WiFi', 'Fast and reliable internet connection throughout the property.'),
('Fireplace', 'Cozy indoor fireplace to warm up during chilly nights.'),
('Grill', 'Outdoor grill available for barbecuing with friends or family.'),
('Gym', 'Access to gym equipment.'),
('Air Conditioning', 'Stay cool with air conditioning in all rooms.'),
('Pet-Friendly', 'Pets are welcome in this accommodation.'),
('Parking', 'Private parking space available for guests.'),
('Elevator', 'Easy access to upper floors with an elevator.'),
('Heating', 'Efficient heating system to keep you comfortable.'),
('Hot Tub', 'Relax in a private or shared hot tub.'),
('Garden', 'Enjoy the outdoor garden with seating areas.'),
('Breakfast Included', 'Complimentary breakfast served daily.'),
('Workspace', 'Dedicated workspace with a desk and comfortable chair.'),
('Dryer', 'In-unit or shared clothes dryer available.'),
('TV', 'Smart TV with cable and streaming services.'),
('Washer', 'Washing machine available for guest use.'),
('Dishwasher', 'Dishwashing machine available for guest use.'),
('Oven', 'Oven for baking the food.'),
('Microwave', 'Microwave for heating/baking the food.');