INSERT INTO `logs` (`admin_id`, `description`, `action_type`, `action_performed _on`, `timestamp`) VALUES
(1, 'Approved a new property listing.', 'property', 5, NOW()),
(2, 'Updated user profile details.', 'user', 12, NOW()),
(3, 'Resolved a support ticket regarding payment issues.', 'support_ticket', 8, NOW()),
(4, 'Manually confirmed a pending booking.', 'booking', 15, NOW()),
(5, 'Deactivated an inactive user account.', 'user', 20, NOW()),
(6, 'Marked a support ticket as in progress.', 'support_ticket', 3, NOW()),
(7, 'Updated pricing details for a property.', 'property', 7, NOW()),
(8, 'Canceled a fraudulent booking.', 'booking', 18, NOW()),
(9, 'Reviewed and approved a host verification request.', 'user', 25, NOW()),
(10, 'Escalated a complex support ticket.', 'support_ticket', 14, NOW()),
(11, 'Changed availability settings for a property.', 'property', 10, NOW()),
(12, 'Updated payment details for a user.', 'user', 30, NOW()),
(13, 'Flagged a support ticket for admin review.', 'support_ticket', 22, NOW()),
(14, 'Extended a guest’s booking due to a request.', 'booking', 5, NOW()),
(15, 'Manually assigned a support agent to a ticket.', 'support_ticket', 19, NOW()),
(16, 'Removed a duplicate property listing.', 'property', 9, NOW()),
(17, 'Suspended a user account for violation of terms.', 'user', 40, NOW()),
(18, 'Reviewed a guest refund request.', 'booking', 12, NOW()),
(19, 'Resolved a host dispute through mediation.', 'support_ticket', 27, NOW()),
(20, 'Updated a booking after customer request.', 'booking', 33, NOW()),
(21, 'Enabled instant booking for a property.', 'property', 15, NOW()),
(22, 'Sent a warning to a user regarding policy violations.', 'user', 8, NOW()),
(23, 'Closed a resolved support ticket.', 'support_ticket', 4, NOW()),
(24, 'Modified cancellation policy for a property.', 'property', 28, NOW()),
(25, 'Helped a host update their listing images.', 'property', 35, NOW()),
(26, 'Adjusted check-in times for a guest.', 'booking', 22, NOW()),
(27, 'Reviewed a charge dispute for a booking.', 'booking', 37, NOW()),
(28, 'Addressed a user concern regarding verification.', 'user', 18, NOW()),
(29, 'Corrected a double-booking error.', 'booking', 29, NOW()),
(30, 'Assisted in dispute resolution for a booking issue.', 'support_ticket', 39, NOW()),
(31, 'Manually adjusted tax calculations for a booking.', 'booking', 17, NOW()),
(32, 'Reviewed and approved a property update.', 'property', 21, NOW()),
(33, 'Helped a host resolve pricing discrepancies.', 'property', 16, NOW()),
(34, 'Notified a user of a login attempt from a new device.', 'user', 13, NOW()),
(35, 'Updated host payout details.', 'user', 23, NOW()),
(36, 'Investigated a support ticket flagged for review.', 'support_ticket', 6, NOW()),
(37, 'Changed a user’s email address after verification.', 'user', 11, NOW()),
(38, 'Manually processed a refund request.', 'booking', 26, NOW()),
(39, 'Flagged a property listing for suspicious activity.', 'property', 31, NOW()),
(40, 'Resolved a technical issue with a support ticket.', 'support_ticket', 9, NOW());
