ALTER TABLE property AUTO_INCREMENT = 1;
INSERT INTO `property` (`host_id`, `location_id`, `title`, `type`, `capacity`, `main_beds`, `additional_beds`, `description`, `approved`)
VALUES
(2, 1, 'Croatia apartment 1', 'room', 2, 1, 0, 'A beautiful room with a sea view in Split.', 1),
(4, 2, 'Croatia apartment 2', 'apartment', 4, 2, 1, 'Spacious apartment near the city walls.', 1),
(6, 3, 'Croatia apartment 3', 'room', 2, 1, 0, 'Enjoy the historic beauty of Rovinj.', 1),
(8, 4, 'Croatia apartment 4', 'apartment', 6, 3, 2, 'Exclusive villa with a private pool.', 1),
(10, 5, 'Croatia apartment 5', 'room', 2, 1, 0, 'Comfortable stay in the heart of Rijeka.', 0),
(12, 6, 'Croatia apartment 6', 'apartment', 5, 2, 1, 'Direct access to the beach.', 1),
(14, 7, 'Croatia apartment 7', 'room', 2, 1, 0, 'Minimalist studio perfect for a getaway.', 1),
(16, 8, 'Croatia apartment 8', 'apartment', 4, 2, 1, 'Relaxing space near the promenade.', 1),
(18, 9, 'Italy apartment 1', 'apartment', 3, 1, 1, 'Romantic apartment with a view.', 1),
(20, 10, 'Italy apartment 2', 'room', 2, 1, 0, 'Cozy room near the lagoon.', 0),
(2, 11, 'Italy apartment 3', 'apartment', 4, 2, 1, 'Mediterranean charm with sea views.', 1),
(4, 12, 'Italy apartment 4', 'room', 2, 1, 0, 'Elegant room overlooking the sea.', 1),
(6, 13, 'Italy apartment 5', 'apartment', 3, 1, 1, 'Sunny stay by the famous beach.', 0),
(8, 14, 'Italy apartment 6', 'room', 2, 1, 0, 'Perfect for exploring Cinque Terre.', 1),
(10, 15, 'Greece apartment 1', 'apartment', 4, 2, 1, 'Ideal for ferry travelers.', 1),
(12, 16, 'Greece apartment 2', 'room', 2, 1, 0, 'Central location with great views.', 0),
(14, 17, 'Greece apartment 3', 'apartment', 5, 3, 1, 'Spacious and modern.', 1),
(16, 18, 'Greece apartment 4', 'room', 2, 1, 0, 'Experience traditional Greek hospitality.', 1),
(18, 19, 'Greece apartment 5', 'apartment', 3, 1, 1, 'Walk to the Parthenon.', 1),
(20, 20, 'Greece apartment 6', 'room', 2, 1, 0, 'Stay within ancient castle walls.', 0),
(2, 1, 'Croatia apartment 9', 'apartment', 6, 3, 2, 'Spacious penthouse with stunning views.', 1),
(4, 2, 'Croatia apartment 10', 'room', 2, 1, 0, 'Immerse yourself in history.', 1),
(6, 3, 'Croatia apartment 11', 'apartment', 4, 2, 1, 'Steps from the picturesque harbor.', 1),
(8, 4, 'Croatia apartment 12', 'room', 2, 1, 0, 'Relax in a charming seaside cottage.', 0),
(10, 5, 'Croatia apartment 13', 'apartment', 3, 1, 1, 'Bright and stylish.', 1),
(12, 6, 'Croatia apartment 14', 'room', 2, 1, 0, 'Great for families.', 1),
(14, 7, 'Croatia apartment 15', 'apartment', 4, 2, 1, 'Ideal for couples.', 1),
(16, 8, 'Croatia apartment 16', 'room', 2, 1, 0, 'Peaceful and relaxing.', 0),
(18, 9, 'Italy apartment 7', 'apartment', 5, 2, 1, 'Luxury in the heart of Venice.', 1),
(20, 10, 'Italy apartment 8', 'room', 2, 1, 0, 'Relax in nature.', 1),
(22, 1, 'Croatia apartment 17', 'room', 2, 1, 0, 'A beautiful room with a sea view in Split.', 1),
(24, 2, 'Croatia apartment 18', 'apartment', 4, 2, 1, 'Spacious apartment near the city walls.', 1),
(26, 3, 'Croatia apartment 19', 'room', 2, 1, 0, 'Enjoy the historic beauty of Rovinj.', 1),
(28, 4, 'Croatia apartment 20', 'apartment', 6, 3, 2, 'Exclusive villa with a private pool.', 1),
(30, 5, 'Croatia apartment 21', 'room', 2, 1, 0, 'Comfortable stay in the heart of Rijeka.', 0),
(32, 6, 'Croatia apartment 22', 'apartment', 5, 2, 1, 'Direct access to the beach.', 1),
(34, 7, 'Croatia apartment 23', 'room', 2, 1, 0, 'Minimalist studio perfect for a getaway.', 1),
(36, 8, 'Croatia apartment 24', 'apartment', 4, 2, 1, 'Relaxing space near the promenade.', 1),
(38, 9, 'Italy apartment 9', 'apartment', 3, 1, 1, 'Romantic apartment with a view.', 1),
(40, 10, 'Italy apartment 10', 'room', 2, 1, 0, 'Cozy room near the lagoon.', 0),
(22, 11, 'Italy apartment 11', 'apartment', 4, 2, 1, 'Mediterranean charm with sea views.', 1),
(24, 12, 'Italy apartment 12', 'room', 2, 1, 0, 'Elegant room overlooking the sea.', 1),
(26, 13, 'Italy apartment 13', 'apartment', 3, 1, 1, 'Sunny stay by the famous beach.', 0),
(28, 14, 'Italy apartment 14', 'room', 2, 1, 0, 'Perfect for exploring Cinque Terre.', 1),
(30, 15, 'Greece apartment 7', 'apartment', 4, 2, 1, 'Ideal for ferry travelers.', 1),
(32, 16, 'Greece apartment 8', 'room', 2, 1, 0, 'Central location with great views.', 0),
(34, 17, 'Greece apartment 9', 'apartment', 5, 3, 1, 'Spacious and modern.', 1),
(36, 18, 'Greece apartment 10', 'room', 2, 1, 0, 'Experience traditional Greek hospitality.', 1),
(38, 19, 'Greece apartment 11', 'apartment', 3, 1, 1, 'Walk to the Parthenon.', 1),
(40, 20, 'Greece apartment 12', 'room', 2, 1, 0, 'Stay within ancient castle walls.', 0);

