INSERT INTO `rules` (`title`, `description`) VALUES
('No Smoking', 'Smoking is not allowed inside the property. Please use designated outdoor areas if available.'),
('No Pets', 'Pets are not allowed on the premises unless explicitly permitted.'),
('Quiet Hours', 'Please respect quiet hours from 10 PM to 7 AM to ensure a peaceful stay for all guests.'),
('Check-in Time', 'Check-in is available from 3 PM onwards. Early check-in may be possible upon request.'),
('Check-out Time', 'Check-out is required by 11 AM. Late check-out may result in additional charges.'),
('No Parties or Events', 'Large gatherings, parties, or events are strictly prohibited.'),
('Maximum Occupancy', 'The maximum number of guests allowed is as per the booking. No additional guests without prior approval.'),
('Children not allowed', 'Property does not allow children on the premises.'),
('Proper Waste Disposal', 'Dispose of trash in designated bins and follow the recycling rules if applicable.'),
('Lock Doors and Windows', 'Ensure all doors and windows are locked when leaving the property for safety.'),
('No Unauthorized Visitors', 'Only registered guests are allowed in the property. No unauthorized visitors.'),
('Kitchen Use', 'Guests are welcome to use the kitchen but should clean up after themselves.'),
('Damage Policy', 'Any damage to the property or items must be reported immediately. Charges may apply.'),
('Use of Appliances', 'All appliances should be used safely and responsibly. Follow provided instructions.'),
('Parking Rules', 'If parking is available, use the designated spot and follow any local parking regulations.'),
('Pool Safety', 'If a pool is available, children must be supervised at all times.'),
('No Extra Visitors', 'Extra visitors are not allowed'),
('Energy Conservation', 'Please turn off lights, air conditioning, and appliances when not in use.');
