INSERT INTO `support_ticket` (`user_id`, `subject`, `text`, `ticket_status`, `updated_at`) VALUES
(1, 'Login Issue', 'I am unable to log into my account. Please assist.', 'open', NOW()),
(2, 'Payment Not Processed', 'I made a payment, but it is not reflected in my account.', 'closed', NOW()),
(3, 'Bug Report', 'There is a glitch on the booking page when selecting dates.', 'in progress', NOW()),
(4, 'Account Verification', 'I did not receive my verification email.', 'open', NOW()),
(5, 'Refund Request', 'I need a refund for a double-charged transaction.', 'open', NOW()),
(6, 'Feature Request', 'Can you add support for dark mode in the app?', 'in progress', NOW()),
(7, 'Property Listing Issue', 'My property listing is not showing up in search results.', 'closed', NOW()),
(8, 'Incorrect Pricing', 'The price displayed for my listing is incorrect.', 'open', NOW()),
(9, 'Slow Website', 'The website is taking too long to load.', 'in progress', NOW()),
(10, 'Password Reset', 'I forgot my password and cannot reset it.', 'open', NOW()),
(11, 'Booking Cancellation', 'I canceled a booking, but my refund is still pending.', 'closed', NOW()),
(12, 'Two-Factor Authentication', 'I am unable to set up two-factor authentication.', 'in progress', NOW()),
(13, 'Email Notifications', 'I am not receiving booking confirmation emails.', 'open', NOW()),
(14, 'Wrong Charge', 'I was charged incorrectly for my last booking.', 'closed', NOW()),
(15, 'Account Deletion Request', 'I want to delete my account permanently.', 'open', NOW()),
(16, 'Security Concern', 'I noticed unusual activity on my account.', 'in progress', NOW()),
(17, 'Mobile App Issue', 'The app crashes when I try to open messages.', 'closed', NOW()),
(18, 'Host Unresponsive', 'A host is not responding to my inquiries.', 'open', NOW()),
(19, 'Discount Code Not Working', 'The promo code I received does not apply at checkout.', 'closed', NOW()),
(20, 'Feedback and Suggestions', 'I love the platform, but I have some suggestions.', 'in progress', NOW()),
(21, 'Profile Picture Issue', 'I am unable to upload my profile picture.', 'open', NOW()),
(22, 'Check-in Issue', 'The property owner did not show up for my check-in.', 'closed', NOW()),
(23, 'Missing Features', 'Can you add support for multiple currencies in transactions?', 'in progress', NOW()),
(24, 'Language Setting Problem', 'My language settings keep resetting.', 'open', NOW()),
(25, 'Duplicate Booking', 'I accidentally booked the same property twice.', 'closed', NOW()),
(26, 'Review Not Posting', 'My review is not appearing on the property page.', 'in progress', NOW()),
(27, 'Billing Error', 'I was billed for a service I did not use.', 'open', NOW()),
(28, 'Map Not Loading', 'The location map is not displaying correctly.', 'closed', NOW()),
(29, 'Listing Approval Delay', 'My property listing has been under review for too long.', 'in progress', NOW()),
(30, 'No Response from Support', 'I submitted a ticket days ago but received no reply.', 'open', NOW()),
(31, 'Calendar Sync Issue', 'My calendar is not syncing properly with external services.', 'closed', NOW()),
(32, 'Message Not Sending', 'I cannot send messages to potential guests.', 'in progress', NOW()),
(33, 'Check-out Problem', 'The host is not allowing me to check out early.', 'open', NOW()),
(34, 'Wrong Booking Details', 'My booking details were changed without my consent.', 'closed', NOW()),
(35, 'Host Cancelled Last Minute', 'My host canceled my booking at the last moment.', 'in progress', NOW()),
(36, 'Payout Delay', 'I have not received my payout as expected.', 'open', NOW()),
(37, 'New User Registration Issue', 'I cannot register as a new user.', 'closed', NOW()),
(38, 'Lost Item in Property', 'I forgot an item at a booked property and need assistance.', 'in progress', NOW()),
(39, 'Tax Calculation Issue', 'The tax calculation on my invoice seems incorrect.', 'open', NOW()),
(40, 'Service Fee Clarification', 'I want to understand how the service fees are calculated.', 'closed', NOW());
